name: drtree_benchmark
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  args: ^2.4.0
  benchmark_runner:
    path: ../benchmark_runner
  drtree:
    path: ../drtree
  dart_utils:
    path: ../dart_utils

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
